/*
 * Screenshot Capture API
 * Webseite-Herunterladen.de Screenshot Capture is a very simple but powerful screenshot API that anyone can easily use to create pixel-perfect website screenshots. It always uses a recent version of Chrome to ensure that all modern web features are fully supported and rendering is exactly as your customers would expect.
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.26
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from './ApiClient';
import {ErrorModel} from './model/ErrorModel';
import {ScreenshotApi} from './api/ScreenshotApi';

/**
* Webseite_Herunterladen_de_Screenshot_Capture_is_a_very_simple_but_powerful_screenshot_API_that_anyone_can_easily_use_to_create_pixel_perfect_website_screenshots__It_always_uses_a_recent_version_of_Chrome_to_ensure_that_all_modern_web_features_are_fully_supported_and_rendering_is_exactly_as_your_customers_would_expect_.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var ScreenshotCaptureApi = require('index'); // See note below*.
* var xxxSvc = new ScreenshotCaptureApi.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new ScreenshotCaptureApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new ScreenshotCaptureApi.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new ScreenshotCaptureApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 1.0.0
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The ErrorModel model constructor.
     * @property {module:model/ErrorModel}
     */
    ErrorModel,

    /**
    * The ScreenshotApi service constructor.
    * @property {module:api/ScreenshotApi}
    */
    ScreenshotApi
};
