/*
 * Screenshot Capture API
 * screenshot-capture-api.com Screenshot Capture is a very simple but powerful screenshot API that anyone can easily use to create pixel-perfect website screenshots. It always uses a recent version of Chrome to ensure that all modern web features are fully supported and rendering is exactly as your customers would expect.
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.26
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ScreenshotCaptureApi);
  }
}(this, function(expect, ScreenshotCaptureApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new ScreenshotCaptureApi.ScreenshotApi();
  });

  describe('(package)', function() {
    describe('ScreenshotApi', function() {
      describe('captureScreenshotAuthenticated', function() {
        it('should call captureScreenshotAuthenticated successfully', function(done) {
          // TODO: uncomment, update parameter values for captureScreenshotAuthenticated call and complete the assertions
          /*
          var opts = {};

          instance.captureScreenshotAuthenticated(token, hash, url, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(Blob);
            // expect(data).to.be(null);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('captureScreenshotUnauthenticated', function() {
        it('should call captureScreenshotUnauthenticated successfully', function(done) {
          // TODO: uncomment, update parameter values for captureScreenshotUnauthenticated call and complete the assertions
          /*
          var opts = {};

          instance.captureScreenshotUnauthenticated(token, url, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(Blob);
            // expect(data).to.be(null);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
