/**
 * Webseite-Herunterladen.de Screenshot Capture API
 * Webseite-Herunterladen.de Screenshot Capture is a very simple but powerful screenshot API that anyone can easily use to create pixel-perfect website screenshots. It always uses a recent version of Chrome to ensure that all modern web features are fully supported and rendering is exactly as your customers would expect.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.WebseiteHerunterladenDeScreenshotCaptureApi);
  }
}(this, function(expect, WebseiteHerunterladenDeScreenshotCaptureApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new WebseiteHerunterladenDeScreenshotCaptureApi.ScreenshotApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ScreenshotApi', function() {
    describe('placeScreenshotOrderAuthenticated', function() {
      it('should call placeScreenshotOrderAuthenticated successfully', function(done) {
        //uncomment below and update the code to test placeScreenshotOrderAuthenticated
        //instance.placeScreenshotOrderAuthenticated(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('placeScreenshotOrderUnauthenticated', function() {
      it('should call placeScreenshotOrderUnauthenticated successfully', function(done) {
        //uncomment below and update the code to test placeScreenshotOrderUnauthenticated
        //instance.placeScreenshotOrderUnauthenticated(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
